---
title             : "Benefits and risks associated with children’s and adolescents’ interactions with electronic screens: An umbrella review"
shorttitle        : "Benefits and risks of electronic screens"

author: 
  - name          : "Taren Sanders"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "33 Berry St, North Sydney, NSW, Australia"
    email         : "Taren.Sanders@acu.edu.au"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Data curation
      - Writing - Original Draft
  - name          : "Michael Noetel"
    affiliation   : "2"
    role:
      - Conceptualization
      - Writing - Original Draft
  - name          : "Philip Parker"
    affiliation   : "1"
    role:
      - Conceptualization
      - Writing - Original Draft
  - name          : "Borja Del Pozo Cruz"
    affiliation   : "3"
    role:
      - Writing - Review & Editing
  - name          : "Stuart Biddle"
    affiliation   : "4"
    role:
      - Writing - Review & Editing
  - name          : "Rimante Ronto"
    affiliation   : "5"
    role:
      - Writing - Review & Editing
  - name          : "Ryan Hulteen"
    affiliation   : "6"
    role:
      - Writing - Review & Editing
  - name          : "Rhiannon Parker"
    affiliation   : "7"
    role:
      - Writing - Review & Editing
  - name          : "George Thomas"
    affiliation   : "8"
    role:
      - Writing - Review & Editing
  - name          : "Katrien De Cocker"
    affiliation   : "5"
    role:
      - Writing - Review & Editing
  - name          : "Jo Salmon"
    affiliation   : "9"
    role:
      - Writing - Review & Editing
  - name          : "Kylie Hesketh"
    affiliation   : "9"
    role:
      - Writing - Review & Editing
  - name          : "Nicole Weeks"
    affiliation   : "1"
    role:
      - Writing - Review & Editing
  - name          : "Hugh Arnott"
    affiliation   : "1"
    role:
      - Writing - Review & Editing
  - name          : "Emma Devine"
    affiliation   : "10"
    role:
      - Writing - Review & Editing
  - name          : "Roberta Vasconcellos"
    affiliation   : "1"
    role:
      - Writing - Review & Editing
  - name          : "Chris Lonsdale"
    affiliation   : "1"
    role:
      - Writing - Original Draft
      - Project Administration
                          

affiliation:
  - id            : "1"
    institution   : "Institute for Positive Psychology and Education, Australian Catholic University"
  - id            : "2"
    institution   : "School of Health and Behavioural Sciences, Australian Catholic University"
  - id            : "3"
    institution   : "Department of Sport Science and Clinical Biomechanics, University of Southern Denmark"
  - id            : "4"
    institution   : "School of Psychology and Counselling, University of Southern Queensland"
  - id            : "5"
    institution   : "Department of Health Systems and Populations, Faculty of Medicine, Health and Human Sciences, Macquarie University"
  - id            : "6"
    institution   : "School of Kinesiology, Louisiana State University"
  - id            : "7"
    institution   : "School of Medicine and Health, Sydney University"
  - id            : "8"
    institution   : "Faculty of Health Sciences, Curtin University"
  - id            : "9"
    institution   : "Institute for Physical Activity and Nutrition, Deakin University"
  - id            : "10"
    institution   : "The Matilda Centre for Research in Mental Health and Substance Use, University of Sydney"
    
  
authornote: |
  Add author notes here

abstract: |
  Add abstract here
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["combined.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : yes

documentclass     : "apa6"
classoption       : "man"
csl               : vancouver-brackets-meta.csl
output            : papaja::apa6_pdf
nocite            : "`r params$nocite_list`"
params:
  render_img: true
  nocite_list : true
  inc_tabs: false
---

```{r setup, include=FALSE}
Sys.setenv("RSTUDIO_VERSION" = '1.4.1725')
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

options(dplyr.summarise.inform = FALSE)

# Uncomment to run outside of pipeline
# library(tidyverse)
# library(targets)
# library(xfun)
```


```{r child = 'manuscript_content.Rmd'}
```


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
References marked with an asterisk indicate studies which were included in the synthesis.
<div id = "refs"></div>
\endgroup
